"""add_doe_set_point_percentage

Revision ID: 0b771a8bb55d
Revises: 54595fc3f784
Create Date: 2025-07-11 10:58:12.639166

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0b771a8bb55d"
down_revision = "54595fc3f784"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_aggregator_certificate_assignment_cert_id_agg_id", "aggregator_certificate_assignment", type_="unique"
    )
    op.create_unique_constraint(
        "uq_aggregator_certificate_assignment_cert_id_agg_id",
        "aggregator_certificate_assignment",
        ["assignment_id", "certificate_id"],
    )
    op.add_column(
        "archive_dynamic_operating_envelope",
        sa.Column("set_point_percentage", sa.DECIMAL(precision=16, scale=2), nullable=True),
    )
    op.add_column(
        "dynamic_operating_envelope",
        sa.Column("set_point_percentage", sa.DECIMAL(precision=16, scale=2), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dynamic_operating_envelope", "set_point_percentage")
    op.drop_column("archive_dynamic_operating_envelope", "set_point_percentage")
    op.drop_constraint(
        "uq_aggregator_certificate_assignment_cert_id_agg_id", "aggregator_certificate_assignment", type_="unique"
    )
    op.create_unique_constraint(
        "uq_aggregator_certificate_assignment_cert_id_agg_id",
        "aggregator_certificate_assignment",
        ["certificate_id", "aggregator_id"],
    )
    # ### end Alembic commands ###
