"""nullable_der_archive

Revision ID: 2593d6e055bb
Revises: ab6361a582b3
Create Date: 2026-07-28 11:53:52.609607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2593d6e055bb'
down_revision = 'ab6361a582b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('archive_site_der_availability', 'site_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('archive_site_der_rating', 'site_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('archive_site_der_setting', 'site_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('archive_site_der_status', 'site_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('archive_site_der_status', 'site_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('archive_site_der_setting', 'site_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('archive_site_der_rating', 'site_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('archive_site_der_availability', 'site_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
