"""does_end_time

Revision ID: 33a17317e7ff
Revises: caa470b0f83a
Create Date: 2025-05-10 21:32:56.680280

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "33a17317e7ff"
down_revision = "caa470b0f83a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "archive_dynamic_operating_envelope", sa.Column("end_time", sa.DateTime(timezone=True), nullable=False)
    )
    op.create_index(
        "archive_doe_end_time_deleted_time_site_id",
        "archive_dynamic_operating_envelope",
        ["end_time", "deleted_time", "site_id"],
        unique=False,
    )
    op.add_column(
        "dynamic_operating_envelope",
        sa.Column(
            "end_time",
            sa.DateTime(timezone=True),
            sa.Computed("date_add(start_time, duration_seconds * interval '1 sec', 'UTC')", persisted=True),
            nullable=False,
        ),
    )
    op.drop_constraint("site_id_start_time_uc", "dynamic_operating_envelope", type_="unique")
    op.create_index(
        "ix_dynamic_operating_envelope_end_time_site_id",
        "dynamic_operating_envelope",
        ["end_time", "site_id"],
        unique=False,
    )
    op.create_unique_constraint("start_time_site_id_uc", "dynamic_operating_envelope", ["start_time", "site_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("start_time_site_id_uc", "dynamic_operating_envelope", type_="unique")
    op.drop_index("ix_dynamic_operating_envelope_end_time_site_id", table_name="dynamic_operating_envelope")
    op.create_unique_constraint("site_id_start_time_uc", "dynamic_operating_envelope", ["site_id", "start_time"])
    op.drop_column("dynamic_operating_envelope", "end_time")
    op.drop_index("archive_doe_end_time_deleted_time_site_id", table_name="archive_dynamic_operating_envelope")
    op.drop_column("archive_dynamic_operating_envelope", "end_time")
    # ### end Alembic commands ###
