"""pricing_poll_rates

Revision ID: 7abb815cdbb3
Revises: a25be5a186ba
Create Date: 2026-04-09 13:07:09.469764

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7abb815cdbb3"
down_revision = "a25be5a186ba"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("runtime_server_config", sa.Column("tp_pollrate_seconds", sa.INTEGER(), nullable=True))
    op.add_column("runtime_server_config", sa.Column("tti_pollrate_seconds", sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("runtime_server_config", "tti_pollrate_seconds")
    op.drop_column("runtime_server_config", "tp_pollrate_seconds")
    # ### end Alembic commands ###
