"""v13_pricing

Revision ID: a25be5a186ba
Revises: ed20565cc862
Create Date: 2026-03-05 11:35:14.635916

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a25be5a186ba"
down_revision = "ed20565cc862"
branch_labels = None
depends_on = None


def upgrade() -> None:

    # -------- Migration code -------
    op.execute("DELETE FROM tariff_generated_rate;")  # Currently not migrating prices
    op.execute("DELETE FROM archive_tariff_generated_rate;")  # Currently not migrating prices
    op.execute("DELETE FROM tariff;")  # Currently not migrating prices
    op.execute("DELETE FROM archive_tariff;")  # Currently not migrating prices

    # Existing price subscriptions will need to be removed as we don't have a way of populating the new
    # resource_parent_id that applies to these specific sub types
    op.execute("DELETE FROM subscription WHERE resource_type = 3;")
    op.execute("DELETE FROM archive_subscription WHERE resource_type = 3;")
    # -------------------------------

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "archive_tariff_component",
        sa.Column("tariff_component_id", sa.BigInteger(), nullable=False),
        sa.Column("tariff_id", sa.INTEGER(), nullable=False),
        sa.Column("description", sa.VARCHAR(length=32), nullable=True),
        sa.Column("version", sa.INTEGER(), nullable=True),
        sa.Column("role_flags", sa.INTEGER(), nullable=False),
        sa.Column("accumulation_behaviour", sa.INTEGER(), nullable=True),
        sa.Column("commodity", sa.INTEGER(), nullable=True),
        sa.Column("data_qualifier", sa.INTEGER(), nullable=True),
        sa.Column("flow_direction", sa.INTEGER(), nullable=True),
        sa.Column("kind", sa.INTEGER(), nullable=True),
        sa.Column("phase", sa.INTEGER(), nullable=True),
        sa.Column("power_of_ten_multiplier", sa.INTEGER(), nullable=True),
        sa.Column("uom", sa.INTEGER(), nullable=True),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("changed_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archive_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("archive_time", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("deleted_time", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("archive_id"),
    )
    op.create_index(
        op.f("ix_archive_tariff_component_deleted_time"), "archive_tariff_component", ["deleted_time"], unique=False
    )
    op.create_index(
        op.f("ix_archive_tariff_component_tariff_component_id"),
        "archive_tariff_component",
        ["tariff_component_id"],
        unique=False,
    )
    op.create_table(
        "tariff_component",
        sa.Column("tariff_component_id", sa.BigInteger(), nullable=False),
        sa.Column("tariff_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.VARCHAR(length=32), nullable=True),
        sa.Column("version", sa.INTEGER(), nullable=True),
        sa.Column("role_flags", sa.INTEGER(), nullable=False),
        sa.Column("accumulation_behaviour", sa.INTEGER(), nullable=True),
        sa.Column("commodity", sa.INTEGER(), nullable=True),
        sa.Column("data_qualifier", sa.INTEGER(), nullable=True),
        sa.Column("flow_direction", sa.INTEGER(), nullable=True),
        sa.Column("kind", sa.INTEGER(), nullable=True),
        sa.Column("phase", sa.INTEGER(), nullable=True),
        sa.Column("power_of_ten_multiplier", sa.INTEGER(), nullable=True),
        sa.Column("uom", sa.INTEGER(), nullable=True),
        sa.Column("created_time", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("changed_time", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tariff_id"],
            ["tariff.tariff_id"],
        ),
        sa.PrimaryKeyConstraint("tariff_component_id"),
    )
    op.create_index(op.f("ix_tariff_component_changed_time"), "tariff_component", ["changed_time"], unique=False)
    op.create_index("ix_tariff_component_tariff_id", "tariff_component", ["tariff_id"], unique=False)
    op.add_column("archive_tariff", sa.Column("price_power_of_ten_multiplier", sa.INTEGER(), nullable=True))
    op.add_column("archive_tariff", sa.Column("primacy", sa.INTEGER(), nullable=False))
    op.add_column("archive_tariff", sa.Column("version", sa.INTEGER(), nullable=True))
    op.add_column("archive_tariff_generated_rate", sa.Column("tariff_component_id", sa.BigInteger(), nullable=False))
    op.add_column("archive_tariff_generated_rate", sa.Column("end_time", sa.DateTime(timezone=True), nullable=False))
    op.add_column("archive_tariff_generated_rate", sa.Column("price_pow10_encoded", sa.INTEGER(), nullable=False))
    op.add_column(
        "archive_tariff_generated_rate", sa.Column("block_1_start_pow10_encoded", sa.INTEGER(), nullable=True)
    )
    op.add_column(
        "archive_tariff_generated_rate", sa.Column("price_pow10_encoded_block_1", sa.INTEGER(), nullable=True)
    )

    op.create_index(
        "archive_tariff_generated_rate_tariff_id_end_deleted_time_site",
        "archive_tariff_generated_rate",
        ["tariff_id", "end_time", "deleted_time", "site_id"],
        unique=False,
    )
    op.create_index(
        "archive_tariff_generated_rate_tc_id_end_deleted_time_site",
        "archive_tariff_generated_rate",
        ["tariff_component_id", "end_time", "deleted_time", "site_id"],
        unique=False,
    )
    op.drop_column("archive_tariff_generated_rate", "export_reactive_price")
    op.drop_column("archive_tariff_generated_rate", "import_active_price")
    op.drop_column("archive_tariff_generated_rate", "export_active_price")
    op.drop_column("archive_tariff_generated_rate", "import_reactive_price")
    op.add_column("tariff", sa.Column("price_power_of_ten_multiplier", sa.INTEGER(), nullable=True))
    op.add_column("tariff", sa.Column("primacy", sa.INTEGER(), nullable=False))
    op.add_column("tariff", sa.Column("version", sa.INTEGER(), nullable=True))
    op.add_column("tariff_generated_rate", sa.Column("tariff_component_id", sa.BigInteger(), nullable=False))
    op.add_column("tariff_generated_rate", sa.Column("end_time", sa.DateTime(timezone=True), nullable=False))
    op.add_column("tariff_generated_rate", sa.Column("price_pow10_encoded", sa.INTEGER(), nullable=False))
    op.add_column("tariff_generated_rate", sa.Column("block_1_start_pow10_encoded", sa.INTEGER(), nullable=True))
    op.add_column("tariff_generated_rate", sa.Column("price_pow10_encoded_block_1", sa.INTEGER(), nullable=True))
    op.drop_constraint("tariff_id_site_id_start_time_uc", "tariff_generated_rate", type_="unique")
    op.create_index(
        "ix_tariff_generated_rate_tariff_component_id_end_time_site_id",
        "tariff_generated_rate",
        ["tariff_component_id", "end_time", "site_id"],
        unique=False,
    )
    op.create_index(
        "ix_tariff_generated_rate_tariff_id_end_time_site_id",
        "tariff_generated_rate",
        ["tariff_id", "end_time", "site_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "tariff_generated_rate", "tariff_component", ["tariff_component_id"], ["tariff_component_id"]
    )
    op.drop_column("tariff_generated_rate", "export_reactive_price")
    op.drop_column("tariff_generated_rate", "import_active_price")
    op.drop_column("tariff_generated_rate", "export_active_price")
    op.drop_column("tariff_generated_rate", "import_reactive_price")

    op.drop_column("tariff_generated_rate_response", "pricing_reading_type")

    op.add_column("subscription", sa.Column("resource_parent_id", sa.INTEGER(), nullable=True))

    op.add_column("archive_subscription", sa.Column("resource_parent_id", sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:

    # -------- Migration code -------
    op.execute("DELETE FROM tariff_generated_rate;")  # Currently not migrating prices
    op.execute("DELETE FROM archive_tariff_generated_rate;")  # Currently not migrating prices
    op.execute("DELETE FROM tariff_component;")  # Currently not migrating prices
    op.execute("DELETE FROM archive_tariff_component;")  # Currently not migrating prices
    op.execute("DELETE FROM tariff;")  # Currently not migrating prices
    op.execute("DELETE FROM archive_tariff;")  # Currently not migrating prices

    # Existing price subscriptions will need to be removed as we don't have a way of populating the new
    # resource_parent_id that applies to these specific sub types
    op.execute("DELETE FROM subscription WHERE resource_type in (3,12,14);")
    op.execute("DELETE FROM archive_subscription WHERE resource_type in (3,12,14);")
    # -------------------------------

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscription", "resource_parent_id")
    op.drop_column("archive_subscription", "resource_parent_id")
    op.add_column("tariff_generated_rate_response", sa.Column("pricing_reading_type", sa.SMALLINT(), nullable=False))

    op.add_column(
        "tariff_generated_rate",
        sa.Column("import_reactive_price", sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    )
    op.add_column(
        "tariff_generated_rate",
        sa.Column("export_active_price", sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    )
    op.add_column(
        "tariff_generated_rate",
        sa.Column("import_active_price", sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    )
    op.add_column(
        "tariff_generated_rate",
        sa.Column("export_reactive_price", sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    )
    op.drop_index("ix_tariff_generated_rate_tariff_id_end_time_site_id", table_name="tariff_generated_rate")
    op.drop_index("ix_tariff_generated_rate_tariff_component_id_end_time_site_id", table_name="tariff_generated_rate")
    op.create_unique_constraint(
        "tariff_id_site_id_start_time_uc",
        "tariff_generated_rate",
        ["tariff_id", "site_id", "start_time"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("tariff_generated_rate", "block_1_start_pow10_encoded")
    op.drop_column("tariff_generated_rate", "price_pow10_encoded_block_1")
    op.drop_column("tariff_generated_rate", "price_pow10_encoded")
    op.drop_column("tariff_generated_rate", "end_time")
    op.drop_column("tariff_generated_rate", "tariff_component_id")
    op.drop_column("tariff", "primacy")
    op.drop_column("tariff", "price_power_of_ten_multiplier")
    op.drop_column("tariff", "version")
    op.add_column(
        "archive_tariff_generated_rate",
        sa.Column("import_reactive_price", sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    )
    op.add_column(
        "archive_tariff_generated_rate",
        sa.Column("export_active_price", sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    )
    op.add_column(
        "archive_tariff_generated_rate",
        sa.Column("import_active_price", sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    )
    op.add_column(
        "archive_tariff_generated_rate",
        sa.Column("export_reactive_price", sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    )
    op.drop_index(
        "archive_tariff_generated_rate_tc_id_end_deleted_time_site", table_name="archive_tariff_generated_rate"
    )
    op.drop_index(
        "archive_tariff_generated_rate_tariff_id_end_deleted_time_site", table_name="archive_tariff_generated_rate"
    )
    op.drop_column("archive_tariff_generated_rate", "block_1_start_pow10_encoded")
    op.drop_column("archive_tariff_generated_rate", "price_pow10_encoded_block_1")
    op.drop_column("archive_tariff_generated_rate", "price_pow10_encoded")
    op.drop_column("archive_tariff_generated_rate", "end_time")
    op.drop_column("archive_tariff_generated_rate", "tariff_component_id")
    op.drop_column("archive_tariff", "primacy")
    op.drop_column("archive_tariff", "price_power_of_ten_multiplier")
    op.drop_column("archive_tariff", "version")
    op.drop_index("ix_tariff_component_tariff_id", table_name="tariff_component")
    op.drop_index(op.f("ix_tariff_component_changed_time"), table_name="tariff_component")
    op.drop_table("tariff_component")
    op.drop_index(op.f("ix_archive_tariff_component_tariff_component_id"), table_name="archive_tariff_component")
    op.drop_index(op.f("ix_archive_tariff_component_deleted_time"), table_name="archive_tariff_component")
    op.drop_table("archive_tariff_component")
    # ### end Alembic commands ###
