"""increase price decimal precision

Revision ID: c70fccf48abd
Revises: ed20565cc862
Create Date: 2026-01-20 12:55:17.067243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c70fccf48abd'
down_revision = 'ed20565cc862'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Update main tariff_generated_rate table
    op.alter_column('tariff_generated_rate', 'import_active_price',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.DECIMAL(precision=10, scale=6),
               existing_nullable=False)
    op.alter_column('tariff_generated_rate', 'export_active_price',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.DECIMAL(precision=10, scale=6),
               existing_nullable=False)
    op.alter_column('tariff_generated_rate', 'import_reactive_price',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.DECIMAL(precision=10, scale=6),
               existing_nullable=False)
    op.alter_column('tariff_generated_rate', 'export_reactive_price',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.DECIMAL(precision=10, scale=6),
               existing_nullable=False)
    
    # Update archive_tariff_generated_rate table
    op.alter_column('archive_tariff_generated_rate', 'import_active_price',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.DECIMAL(precision=10, scale=6),
               existing_nullable=False)
    op.alter_column('archive_tariff_generated_rate', 'export_active_price',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.DECIMAL(precision=10, scale=6),
               existing_nullable=False)
    op.alter_column('archive_tariff_generated_rate', 'import_reactive_price',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.DECIMAL(precision=10, scale=6),
               existing_nullable=False)
    op.alter_column('archive_tariff_generated_rate', 'export_reactive_price',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.DECIMAL(precision=10, scale=6),
               existing_nullable=False)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert main tariff_generated_rate table
    op.alter_column('tariff_generated_rate', 'export_reactive_price',
               existing_type=sa.DECIMAL(precision=10, scale=6),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('tariff_generated_rate', 'import_reactive_price',
               existing_type=sa.DECIMAL(precision=10, scale=6),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('tariff_generated_rate', 'export_active_price',
               existing_type=sa.DECIMAL(precision=10, scale=6),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('tariff_generated_rate', 'import_active_price',
               existing_type=sa.DECIMAL(precision=10, scale=6),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=False)
    
    # Revert archive_tariff_generated_rate table
    op.alter_column('archive_tariff_generated_rate', 'export_reactive_price',
               existing_type=sa.DECIMAL(precision=10, scale=6),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('archive_tariff_generated_rate', 'import_reactive_price',
               existing_type=sa.DECIMAL(precision=10, scale=6),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('archive_tariff_generated_rate', 'export_active_price',
               existing_type=sa.DECIMAL(precision=10, scale=6),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('archive_tariff_generated_rate', 'import_active_price',
               existing_type=sa.DECIMAL(precision=10, scale=6),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###