"""rename dynamic_operating_envelope_id to snapshot and remove FK

Revision ID: f0f12c93d5aa
Revises: d932ac3553a3
Create Date: 2025-08-05 14:13:04.304152

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f0f12c93d5aa"
down_revision = "d932ac3553a3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dynamic_operating_envelope_response",
        sa.Column("dynamic_operating_envelope_id_snapshot", sa.INTEGER(), nullable=False),
    )
    op.drop_constraint(
        "dynamic_operating_envelope_re_dynamic_operating_envelope_i_fkey",
        "dynamic_operating_envelope_response",
        type_="foreignkey",
    )
    op.drop_column("dynamic_operating_envelope_response", "dynamic_operating_envelope_id")
    op.add_column(
        "tariff_generated_rate_response", sa.Column("tariff_generated_rate_id_snapshot", sa.INTEGER(), nullable=False)
    )
    op.drop_constraint(
        "tariff_generated_rate_response_tariff_generated_rate_id_fkey",
        "tariff_generated_rate_response",
        type_="foreignkey",
    )
    op.drop_column("tariff_generated_rate_response", "tariff_generated_rate_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tariff_generated_rate_response",
        sa.Column("tariff_generated_rate_id", sa.BIGINT(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "tariff_generated_rate_response_tariff_generated_rate_id_fkey",
        "tariff_generated_rate_response",
        "tariff_generated_rate",
        ["tariff_generated_rate_id"],
        ["tariff_generated_rate_id"],
        ondelete="CASCADE",
    )
    op.drop_column("tariff_generated_rate_response", "tariff_generated_rate_id_snapshot")
    op.add_column(
        "dynamic_operating_envelope_response",
        sa.Column("dynamic_operating_envelope_id", sa.BIGINT(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "dynamic_operating_envelope_re_dynamic_operating_envelope_i_fkey",
        "dynamic_operating_envelope_response",
        "dynamic_operating_envelope",
        ["dynamic_operating_envelope_id"],
        ["dynamic_operating_envelope_id"],
        ondelete="CASCADE",
    )
    op.drop_column("dynamic_operating_envelope_response", "dynamic_operating_envelope_id_snapshot")
    # ### end Alembic commands ###
