version: '3'

services:
  testdb:
    image: timescale/timescaledb:latest-pg14
    environment:
      # 'POSTGRES_PASSWORD' needs to match the password used in tests/conftest.py
      - POSTGRES_PASSWORD=adminpass
      # If the mapping of the /etc/localtime fails (see volumes section) then comment out that line and
      # uncomment the following two lines (making sure to set the timezone to the same as your host system).
      # - TZ=Australia/Brisbane
      # - PGTZ=Australia/Brisbane
    ports:
      # Expose postgresql on port 5433 to prevent a clash with any local installation of postgresql server (default=5432).
      - 5433:5432
    volumes:
      # Map in the localtime. This results in the timezone of postgresql being set to the same as host system.
      - "/etc/localtime:/etc/localtime:ro"

# Create a new network separate than the one created for docker.compose.yaml
networks:
  default:
    name: envoy-testing
