[tool.black]
line-length = 120

[tool.pytest.ini_options]
pythonpath = ["src/"]
testpaths = "tests"
filterwarnings = ["error::DeprecationWarning"]
addopts = "--strict-markers"
markers = [
    "cert_header: marks tests to use a custom value for cert_header instead of the default",
    "azure_ad_auth: marks tests to enable the azure active directory auth dependency",
]

[tool.bandit]
exclude_dirs = ["tests"]

[tool.mypy]
exclude = ["src/envoy/server/alembic", "tests"]

[build-system]
requires = ["setuptools >= 40.9.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "envoy"
version = "0.0.1"
dependencies = [
    "fastapi",
    "sqlalchemy>=2.0.0",
    "alembic",
    "tzlocal",
    "pydantic_xml[lxml]",
    "python-dateutil",
    "asyncpg",
    "fastapi-async-sqlalchemy",
    "alembic",
    "python-dotenv",
    "uvicorn",
    "pyjwt",
    "cryptography",
    "httpx",
    "envoy_schema @ git+ssh://git@github.com/bsgip/envoy-schema.git",
]

[project.optional-dependencies]
dev = [
    "bandit",
    "flake8",
    "mypy",
    "sqlalchemy[mypy]",
    "types-python-dateutil",
    "types-tzlocal",
    "black",
]
test = [
    "pytest",
    "pytest-asyncio",
    "anyio",
    "pytest-mock",
    "pytest-postgresql",
    "psycopg",
    "httpx",
    "defusedxml",
]

[tool.setuptools.package-data]
"envoy" = ["py.typed"]
