[tool.pytest.ini_options]
pythonpath = ["src/"]
testpaths = "tests"

[tool.bandit]
exclude_dirs = ["tests"]

[build-system]
requires = ["setuptools >= 40.9.0", "wheel"]
build-backend = "setuptools.build_meta"